//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("VersionOne, Inc")]
[assembly: AssemblyCopyright("Copyright 2012, VersionOne, Inc. Licensed under modified BSD.")]
[assembly: AssemblyVersion("12.2.0.0")]
[assembly: AssemblyFileVersion("12.2.0.0")]
[assembly: AssemblyInformationalVersion("12.2.1.3588 Summer 2012")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("VersionOne.SDK.APIClient")]
[assembly: AssemblyTitle("VersionOne SDK API Client")]
[assembly: AssemblyDescription("VersionOne SDK .NET API Client Release Build")]