// Auto generated by build.sh at Mon Dec  9 15:25:38 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("14.1.0.1016")]
[assembly: AssemblyFileVersion("14.1.0.1016")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.SDK.NET.APIClient/wiki")]

[assembly: AssemblyProduct("APIClient")]
[assembly: AssemblyTitle("VersionOne SDK API Client")]
[assembly: AssemblyDescription("VersionOne SDK .NET API Client APIClient Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
