// Auto generated by build_universal.sh at Mon Jan 28 16:46:39 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("No version information generated.")]
[assembly: AssemblyDescription("VersionOne SDK .NET API Client Tests Dev Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyProduct("VersionOne.SDK.APIClient.Tests")]
[assembly: AssemblyTitle("VersionOne SDK .NET API Client Tests Dev Build")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc. Licensed under modified BSD.")]
[assembly: AssemblyConfiguration("Debug")]

